default_stages: [commit, push]
exclude: ^src/bin/
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
    -   id: check-added-large-files
        args: [--maxkb=100]

    -   id: check-merge-conflict

    -   id: end-of-file-fixer
        types: [python]

    -   id: fix-encoding-pragma
        args: [--remove]

    -   id: file-contents-sorter
        files: .gitignore

    -   id: forbid-new-submodules

    -   id: trailing-whitespace
        types: [python]

-   repo: https://gitlab.com/pycqa/flake8
    rev: a7be77f7
    hooks:
    -   id: flake8
        args: [--select=W504, --ignore=E501,W503]

-   repo: https://github.com/pre-commit/mirrors-pylint
    rev: v2.3.1
    hooks:
    -   id: pylint
        language: system
        args: [--rcfile=.pylintrc]

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.20
    hooks:
    -   id: isort
